[package]
name = "ferrum2-dns"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
hickory-proto.workspace = true
hickory-resolver.workspace = true
hickory-server.workspace = true

[lints]
workspace = true
