[package]
name = "ferrum2-shadowsocks"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[features]
default = []
tokio = ["dep:tokio"]

[dependencies]
ferrum2-core.workspace = true
ferrum2-crypto.workspace = true
bytes.workspace = true
thiserror.workspace = true
zeroize.workspace = true
tokio = { workspace = true, optional = true }

[dev-dependencies]
hex.workspace = true
serde_json.workspace = true
stats_alloc.workspace = true
tokio.workspace = true

[lints]
workspace = true
