[package]
name = "ferrum2-tun"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
ferrum2-runtime.workspace = true
smoltcp.workspace = true
tokio.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }

[target.'cfg(all(windows, target_arch = "x86_64"))'.dependencies]
ferrum2-wintun.workspace = true

[lints]
workspace = true
