[package]
name = "ferrum2-rocom"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = []
decode = ["dep:aws-lc-rs", "dep:clap", "dep:sha2", "dep:prost-reflect", "dep:protox", "dep:tempfile"]

[dependencies]
base64.workspace = true
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
zeroize.workspace = true
aws-lc-rs = { workspace = true, optional = true }
clap = { workspace = true, optional = true }
sha2 = { workspace = true, optional = true }
prost-reflect = { workspace = true, optional = true }
protox = { workspace = true, optional = true }
tempfile = { workspace = true, optional = true }

[dev-dependencies]
aes.workspace = true
tempfile.workspace = true

[[bin]]
name = "ferrum2-rocom-decode"
path = "src/bin/decode.rs"
required-features = ["decode"]

[lints]
workspace = true
