[package]
name = "ferrum2-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "ferrum2-client"
path = "src/main.rs"

[dependencies]
ferrum2-config.workspace = true
ferrum2-core.workspace = true
ferrum2-crypto.workspace = true
ferrum2-observability.workspace = true
ferrum2-runtime.workspace = true
ferrum2-shadowsocks.workspace = true
ferrum2-socks5.workspace = true
clap.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }

[lints]
workspace = true
